### ISSUE TITLE
online player count problem

### ISSUE THREAD

**Issue by omertelli** [thecrock/rehlds-nosteam#1]
Hello , 
we have little problem like this
![players_bug](https://cloud.githubusercontent.com/assets/6948947/8434711/ac6ab4a6-1f55-11e5-83d7-dd1605b9cd59.png)

**Comment by thecrock** [comment]
Thx for the report!
You seems to be the first person who tried to use my plugin on a server with players :)
It may take several days to make a fix (complicated bug + absence of free time), so please be patient.

**Comment by thecrock** [comment]
Fixed binaries:
https://github.com/thecrock/rehlds-nosteam/releases/tag/v0.1.1
